name: CI for api directory

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path-api
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache-api
        with:
          path: |
            ${{ steps.yarn-cache-dir-path-api.outputs.dir }}
            api/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-api-
          restore-keys: |
            ${{ runner.os }}-yarn-api-

      - name: Install dependencies
        run: yarn --ignore-engines --frozen-lockfile --ignore-scripts
        if: steps.yarn-cache-api.outputs.cache-hit != 'true'

      - name: Build
        run: yarn build

      - name: Lint code
        run: yarn lint
